[package]
name = "PeerLand"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.node]
path = "./node"

[dev-dependencies.cargo-husky]
version = "1.5.0"
features = ["run-cargo-check", "run-cargo-clippy", "run-cargo-fmt"]