[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["net"] }
turmoil = { version = "0.6", optional = true }

[features]
simulation = ["turmoil"]
