[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.65"
tokio = { version = "1.41.0", features = ["sync", "rt-multi-thread", "time"] }
env_logger = "0.11.5"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dependencies.network]
path = "../network"

[features]
simulation = ["network/simulation"]
